# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d85408d2f158d3cabfade1a2463264d73e09aa67ca16da9a41a65e87d021497ed8a6ef5fcb4a5629897a33704cf649a577a8701f06798bc0f5fb92911368cb18

test:
  secret_key_base: b0898c97be0454eb772a6d61c975ecc8020cd285354a52f7cbc636e5c176a02a2ee1a044035e195229807f3febd6883aef366d97ce5c92624af71b680bbf513e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
